<?php

/**
 * Include required scripts and styles
 */
function vandc_enquire()
{
	wp_enqueue_script('js-script', 					get_template_directory_uri() . '/assets/js/jquery-2.1.3.min.js', array( 'jquery' ));
	
	wp_enqueue_script('modernise-modernizr', 		get_template_directory_uri() . '/assets/js/fallback/modernizr.2.8.3.js', array( 'jquery' ), false, true);

	// Fades in items within viewpoint (google can sometimes not render content - you've been warned!)
	wp_enqueue_script('wowjs', 						get_template_directory_uri() . '/assets/libs/wowjs/wow.min.js', array( 'jquery' ));
	wp_enqueue_style('animate-css', 				get_template_directory_uri() . '/assets/libs/wowjs/animate.css');	

	wp_enqueue_style('vitalandcreative-style', 					get_stylesheet_directory_uri() . '/assets/css/styles.css');

	wp_enqueue_script('vandc-script', 				get_stylesheet_directory_uri() . '/assets/js/main.js', array( 'jquery' ));

	// Localize site directory data to javascript
	$url_arr = array(
		'template_dir' 	=> get_template_directory_uri(),
		'base_dir' 		=> get_site_url()
	);
	wp_localize_script( 'vandc-script', 'url_data', $url_arr );
}
add_action('wp_enqueue_scripts', 'vandc_enquire');

/**
 * Function run on theme activation
 */
function vandc_init()
{
    //Register theme supports
    add_theme_support('post-thumbnails');
    add_theme_support( 'html5', array( 'comment-list', 'comment-form', 'search-form', 'gallery', 'caption' ) );

	//Register navigation menus
	
	register_nav_menus(
		array(
			'headernav' => 'header nav',
			'footernav' => 'footer nav'
		)
	);	





	//Customise post type support
	/*
	add_post_type_support('post', 'excerpt');
	remove_post_type_support('post', 'custom-fields');
	remove_post_type_support('post', 'page-attributes');
	*/

	//Add image sizes
	/*
	add_image_size('archive-thumb', 500, 250, true);
	*/
}
add_action('init', 'vandc_init');

/**
 * Add 'menu-parent-item' class to menu parent items generated by wp_nav_menu
 *
 * @param $items
 * @return mixed
 */
function add_menu_parent_class($items)
{
	$parents = array();
	foreach ($items as $item) {
		if ($item->menu_item_parent && $item->menu_item_parent > 0) {
			$parents[] = $item->menu_item_parent;
		}
	}

	foreach ($items as $item) {
		if (in_array($item->ID, $parents)) {
			$item->classes[] = 'menu-parent-item';
		}
	}
	return $items;
}
add_filter('wp_nav_menu_objects', 'add_menu_parent_class');

/**
 * Add 'current-menu-item' class menu to current menu item generated by wp_nav_menu
 *
 * @param $classes
 * @param $item
 * @return array
 */
function add_current_nav_class($classes, $item)
{
	// Getting the current post details
	global $post;

	if( !isset($post) )
		return $classes;

	// Getting the post type of the current post
	$current_post_type = get_post_type_object(get_post_type($post->ID));
	//If not in a post type get the hell out of here
	if( !is_array( $current_post_type_slug = $current_post_type->rewrite ) ){
		return $classes;
	}
	$current_post_type_slug = $current_post_type->rewrite['slug'];

	// Getting the URL of the menu item
	$menu_slug = strtolower(trim($item->url));

	// If the menu item URL contains the current post types slug add the current-menu-item class
	if (strpos($menu_slug,$current_post_type_slug) !== false) {
		$classes[] = 'current-menu-item';
	}

	// Return the corrected set of classes to be added to the menu item
	return $classes;
}
add_action('nav_menu_css_class', 'add_current_nav_class', 10, 2 );

/**
 * Adds a browser class to body tag
 *
 * @param $classes
 * @return array
 */
function browser_body_class($classes) {
	global $is_lynx, $is_gecko, $is_IE, $is_opera, $is_NS4, $is_safari, $is_chrome, $is_iphone;

	if($is_lynx) $classes[] = 'lynx';
	elseif($is_gecko) $classes[] = 'gecko';
	elseif($is_opera) $classes[] = 'opera';
	elseif($is_NS4) $classes[] = 'ns4';
	elseif($is_safari) $classes[] = 'safari';
	elseif($is_chrome) $classes[] = 'chrome';
	elseif($is_IE) $classes[] = 'ie';
	else $classes[] = 'unknown';

	if($is_iphone) $classes[] = 'iphone';
	return $classes;
}
add_filter('body_class','browser_body_class');

// widget support 
register_sidebar(
	array(
		'id' => 'primary',
		'name' => __( 'Primary Sidebar' ),
		'description' => __( 'The following widgets will appear in the main sidebar div.' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget' => '</aside>',
		'before_title' => '<h4>',
		'after_title' => '</h4>'
	)
);
register_sidebar(
	array(
		'id' => 'single',
		'name' => __( 'Single Sidebar' ),
		'description' => __( 'The following widgets will appear on the single post.' ),
		'before_widget' => '<aside id="%1$s" class="widget %2$s">',
		'after_widget' => '</aside>',
		'before_title' => '<h4>',
		'after_title' => '</h4>'
	)
);